#include "../TYPES.H"

unsigned int extra_score;
unsigned char markerno;
unsigned short gdemoflg;
unsigned char emi3end;
unsigned char specialflg;
unsigned char projector_flag;
unsigned char generate_flag;
unsigned short pl_yspd;
unsigned short pl_xspd;
unsigned char time_flag;
unsigned char gameinit;
int game_score;
int pltime;
unsigned short plring;
unsigned char pl_suu;
unsigned short stageno;
unsigned char ufoleftsave;
unsigned char good_flag;
unsigned char endskipflg;
unsigned char white_inflg;
unsigned char stagenm_save;
unsigned char clrspflg_save;
unsigned char nobramflg;
unsigned char modeflg;
unsigned char demono;
unsigned char goodflg;
unsigned char clrstnm_sp;
unsigned char clrstnm;
unsigned short reg1save;
unsigned short rcnt;
int timesave;
unsigned char stage_no;
unsigned char round_no;
unsigned char ta_flag;
unsigned char intflg;
int tv_adr[192];
unsigned char ufoleft;
unsigned char clrspflg;
int_union spe_time;
unsigned short ringno;
unsigned char stagenm;
ushort_union swdata1;
unsigned char spgmmode;
unsigned char clrspflg_m;
unsigned char stagenm_m;
unsigned char comflag_m;
int slidewk[1024];
unsigned short sm_adr0[16384];
int* ib_adr;
int* sg_adr;
int* wordram;
